title: Rochester Flower Company
timezone: America/New_York
description: Craft cannabis cultivation in Rochester, NY
url: https://rochesterflowercompany.com
baseurl: 
markdown: kramdown
exclude:
- README.md
- LICENSE
- CNAME
- ".gitignore"
plugins:
- jekyll-seo-tag
